### ISSUE TITLE
Update pull data synapse vignette

### ISSUE THREAD

**Issue by jalavery** [GENIE-BPC/genieBPC#100]
* Update future work, lung object name
* Update order of vignettes in pkgdown yml

**Comment by karissawhiting** [comment]
You can specify how articles are ordered in the pkgdown > _pkgdown.yml file. Here is an example (see `navbar` section https://github.com/ddsjoberg/gtsummary/blob/main/pkgdown/_pkgdown.yml )

**Comment by karissawhiting** [comment]
<img width="809" alt="Screen Shot 2023-08-08 at 11 16 08 AM" src="https://github.com/GENIE-BPC/genieBPC/assets/10888683/34aafcdd-5644-4c1b-ad1b-3e702a1d05fd">
