### ISSUE TITLE
Incorporate gnomeR into select unique ngs

### ISSUE THREAD

**Issue by jalavery** [GENIE-BPC/genieBPC#102]
* Discussed at gnomeR/genieBPC vignette meeting on 3/14/2023
* Can modify select unique ngs function to output the df of sample IDs and panel IDs needed for the create gene binary function in gnomeR. 
* Can reference gnomeR in documentation 
* If implementing, would update genieBPC vignette and genie vignette in gnomeR package

**Comment by karissawhiting** [comment]
Check column names - are they compatible ?

**Comment by jalavery** [comment]
Column names are not compatible.
No changes to be made to genie R package, karissa & hannah to make an update to gnomeR to throw a warning if the column IDs aren't the same, but will assume the first col is sample ID & second column is panel ID
