### ISSUE TITLE
Change in name and structure from fusions dataset --> structural variant dataset

### ISSUE THREAD

**Issue by slb2240** [GENIE-BPC/genieBPC#111]
Expected change for v14.0 main GENIE public release

**Comment by karissawhiting** [comment]
Ask Ino what difference between SV and fusions

**Comment by jalavery** [comment]
GENIE v14.0 has been released - we can revisit this issue

**Comment by thomasyu888** [comment]
Note: it's not just the change in name, the file format is completely different.

**Comment by thomasyu888** [comment]
Glossed over "structure" in my original comment.  But here's the cbioportal format: https://docs.cbioportal.org/file-formats/#structural-variant-data

**Comment by jalavery** [comment]
For data releases with the GENIE 14.0 data release, the fusions file will be in the correct format
Previously, we had to reformat to match what the portal returned
No longer need to reformat

- `pull_data_synapse()` will need to read in the renamed fusions file, we don't know the name of the file yet but will update at the next data release (bladder consortium). `create_analytic_cohort()` will also require an update to account for the new name.
- Will also update vignettes to document this
