### ISSUE TITLE
Error with pull_data_synapse()

### ISSUE THREAD

**Issue by andreasmeid** [GENIE-BPC/genieBPC#118]
Hi,

I wanted to test the geniePBC package by accessing the synapse data as written in the help files. After connecting with my synapse account, I received the error messages below. Unfortunately, I neither understand them nor have a clue what to change. Do you have an idea what went wrong and how to approach the problem?

Many thanks and kind regards

Andreas 

✔ You are now connected to 'Synapse' as
UKHD_genie for this R session!
> BrCa_ex1 <- pull_data_synapse(
+   
+   cohort = c("BrCa"),
+   
+   version = c("v1.1-consortium")
+   
+ )
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `dplyr::mutate()`:
ℹ In argument: `file_info = map(...)`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `switch()`:
! EXPR must be a length 1 vector
Run `rlang::last_trace()` to see where the error occurred.

> rlang::last_trace()
<error/rlang_error>
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `dplyr::mutate()`:
ℹ In argument: `file_info = map(...)`.
---
Backtrace:
     ▆
  1. ├─genieBPC::pull_data_synapse(cohort = c("BrCa"), version = c("v1.1-consortium"))
  2. │ └─purrr::map(...)
  3. │   └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  4. │     ├─purrr:::with_indexed_errors(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─genieBPC (local) .f(.x[[i]], ...)
  7. │       └─genieBPC::.pull_data_by_cohort(...)
  8. │         └─... %>% ...
  9. ├─dplyr::mutate(...)
 10. ├─dplyr:::mutate.data.frame(...)
 11. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
 12. │   ├─base::withCallingHandlers(...)
 13. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 14. │     └─mask$eval_all_mutate(quo)
 15. │       └─dplyr (local) eval()
 16. ├─purrr::map(...)
 17. │ └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
 18. │   ├─purrr:::with_indexed_errors(...)
 19. │   │ └─base::withCallingHandlers(...)
 20. │   └─genieBPC (local) .f(.x[[i]], ...)
 21. ├─base::.handleSimpleError(...)
 22. │ └─purrr (local) h(simpleError(msg, call))
 23. │   └─cli::cli_abort(c(i = "In index: {i}."), parent = cnd, call = error_call)
 24. │     └─rlang::abort(...)
 25. │       └─rlang:::signal_abort(cnd, .file)
 26. │         └─base::signalCondition(cnd)
 27. └─dplyr (local) `<fn>`(`<rlng_rrr>`)
---
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `switch()`:
! EXPR must be a length 1 vector
---
Backtrace:
     ▆
  1. ├─genieBPC::pull_data_synapse(cohort = c("BrCa"), version = c("v1.1-consortium"))
  2. │ └─purrr::map(...)
  3. │   └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  4. │     ├─purrr:::with_indexed_errors(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─genieBPC (local) .f(.x[[i]], ...)
  7. │       └─genieBPC::.pull_data_by_cohort(...)
  8. │         └─... %>% ...
  9. ├─dplyr::mutate(...)
 10. ├─dplyr:::mutate.data.frame(...)
 11. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
 12. │   ├─base::withCallingHandlers(...)
 13. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 14. │     └─mask$eval_all_mutate(quo)
 15. │       └─dplyr (local) eval()
 16. └─purrr::map(...)
 17.   └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
 18.     ├─purrr:::with_indexed_errors(...)
 19.     │ └─base::withCallingHandlers(...)
 20.     └─genieBPC (local) .f(.x[[i]], ...)
Run rlang::last_trace(drop = FALSE) to see 6 hidden frames.

**Comment by jalavery** [comment]
Hi Andreas,

Thanks for alerting us to this error. Could you please log into Synapse and confirm whether you have sufficient permissions to view the contents of the following folder? https://www.synapse.org/#!Synapse:syn26253353

**Comment by andreasmeid** [comment]
Dear Jessica,

trying to open the ling, I got the error message "Sorry, no access to this page". Apparently, I actually do not have permission, but how to get such permission?

Best wishes

Andreas

**Comment by jalavery** [comment]
Thanks @andreasmeid for checking. Are you a part of one of the institutions that contributes data to Project GENIE? If so, I can connect you with the appropriate contact for getting access to the data. If not, the breast data are scheduled to be publicly released later this year and we will release a package update when that happens. 

A note for our R package team (cc: @karissawhiting): Andreas' error was a result of insufficient permissions for consortium data. We can discuss updating error messaging for `pull_data_synapse()` at our next meeting.

Thank you!

**Comment by andreasmeid** [comment]
Dear Jessica,

No, I am not aware that Heidelberg University Hospital is involved here. So I'll just have to wait for the next update.

Best wishes

Andreas

**Comment by karissawhiting** [comment]
We are going to look into getting a login set up that doesn't have access to consortium so we can test this better.

@jalavery

**Comment by janickweberpals** [comment]
Adding to this issue, this error also shows up for me now after having worked fine for the public datasets in the past.

I am able to successfully connect to Synapse via

```
set_synapse_credentials(
  username = Sys.getenv("SYNAPSE_USERNAME"), 
  password = Sys.getenv("SYNAPSE_PASSWORD")
  )
```

But I also receive the following error when trying to pull the public NSCLC data

`pull_data_synapse(cohort = "NSCLC", version = "v2.0-public")`

Error in `purrr::map()` at GENIE-BPC-genieBPC-cd25d24/R/pull_data_synapse.R:195:3:
ℹ In index: 1.
ℹ With name: NSCLC_v2.0.
Caused by error in `dplyr::mutate()`:
ℹ In argument: `file_info = map(...)`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `entityBundle$fileHandles[[1]]`:
! subscript out of bounds
Run `rlang::last_trace()` to see where the error occurred.

**Comment by jalavery** [comment]
Thank you for your interest in AACR Project GENIE. Access to all data except the main AACR Project GENIE registry and published datasets are currently offline. AACR is working to resolve the issue as soon as possible. Thanks in advance for your patience.

**Comment by jalavery** [comment]
AACR Project GENIE data are back online. The latest dev release of this package includes corrections to previous consortium releases: NSCLC 2.1-consortium release was replaced with the NSCLC 2.3-consortium release and the CRC v1.1-consortium and CRC v1.2-consortium releases were replaced with the CRC v1.3-consortium release. The NSCLC v2.1-consortium, CRC v1.1-consortium, and CRC v1.2-consortium data are no longer available; please update your code accordingly to pull from the replacement data releases.
