### ISSUE TITLE
Add NSCLC v3.1-consortium

### ISSUE THREAD

**Issue by hfuchs5** [GENIE-BPC/genieBPC#137]
Checklist for each data release:

- [x]  Re-run to create df of synapse table IDs, should only require an update to the release_dates tribble to indicate the release date (no longer need to enter manually, but need to review to make sure that automated pull worked as expected)
- [x]  Update pull_data_synapse() tests to include the expected number of rows and columns for the datasets in the release
- [x]  Update each function's documentation to indicate which cohorts are available
- [x]  Add link to analytic data guide in pull_data_synapse()
- [x]  Update each function's vignette to indicate which cohorts are available
- [x]  Review create_analytic_cohort() code to make sure variables are applicable and no changes are needed
- [x]  Add link to analytic data guide in README file
- [x]  Re-create drug_regimen_list dataset (after updating synapse_version)
- [x]  If a new cohort (as opposed to a release of an existing cohort), the tests for synapse_data will need to be updated to reflect whether tumor marker or radiation therapy data are curated for the cohort.
- [x]  If a new cohort, add test for drug_regimen_sunburst()

**Comment by hfuchs5** [comment]
- added Ken's timing paper to README references

**Comment by jalavery** [comment]
> * added Ken's timing paper to README references

thank you! can you also please add sammi's CRC paper? https://pubmed.ncbi.nlm.nih.gov/38329392/

**Comment by hfuchs5** [comment]
> > * added Ken's timing paper to README references
> 
> thank you! can you also please add sammi's CRC paper? https://pubmed.ncbi.nlm.nih.gov/38329392/

Yup now it's in!
