### ISSUE TITLE
Release genieBPC version 1.0

### ISSUE THREAD

**Issue by jalavery** [GENIE-BPC/genieBPC#61]
Prepare for release:

* [x] Create cran-comments.md file
* [ ]  `git pull`
* [x] `goodpractice::gp()`
* [ ]  Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_gtsummary.html)
* [x]  [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x]  `devtools::build_readme()`
* [x]  `urlchecker::url_check()`
* [x]  `devtools::check(remote = TRUE, manual = TRUE)`
* [ ]  `devtools::check_win_devel()`
* [x]  `rhub::check_for_cran()`
* [ ]  `revdepcheck::revdep_check(num_workers = 4)`
* [x]  Update `cran-comments.md`
* [x]  `git push`

Submit to CRAN (initial submission):
* [x]  `devtools::release()`

Submit to CRAN (updates):

* [ ]  `usethis::use_version('patch')`
* [ ]  `devtools::submit_cran()`
* [x]  Approve email

Wait for CRAN...

* [ ]  Accepted 🎉
* [ ]  `git push`
* [ ]  `usethis::use_github_release()`
* [ ]  `usethis::use_dev_version()`
* [ ]  `git push`

**Comment by jalavery** [comment]
* `revdepcheck::revdep_check` gives Error: (converted from warning) package ‘genieBPC’ is not available for this version of R. May only be relevant once package is on CRAN, skipping for now. 
* Other checks ran successfully
* Submitted 7/18/2022 🎉

**Comment by jalavery** [comment]
Received CRAN Comments, updating for resubmission.

Prepare for release:

* [ ] Create cran-comments.md file
* [ ]  `git pull`
* [ ] `goodpractice::gp()`
* [ ]  Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_gtsummary.html)
* [ ]  [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [ ]  `devtools::build_readme()`
* [ ]  `urlchecker::url_check()`
* [ ]  `devtools::check(remote = TRUE, manual = TRUE)`
* [ ]  `devtools::check_win_devel()`
* [ ]  `rhub::check_for_cran()`
* [ ]  `revdepcheck::revdep_check(num_workers = 4)`
* [ ]  Update `cran-comments.md`
* [ ]  `git push`

Submit to CRAN (initial submission):
* [ ]  `devtools::release()`

Submit to CRAN (updates):

* [ ]  `usethis::use_version('patch')`
* [ ]  `devtools::submit_cran()`
* [x]  Approve email

Wait for CRAN...

* [ ]  Accepted 🎉
* [ ]  `git push`
* [ ]  `usethis::use_github_release()`
* [ ]  `usethis::use_dev_version()`
* [ ]  `git push`

**Comment by michaelcurry1123** [comment]
@jalavery  you can close this issue now!!
