### ISSUE TITLE
Update error message and documentation in `set_synapse_credentials() 

### ISSUE THREAD

**Issue by karissawhiting** [GENIE-BPC/genieBPC#66]
Relevant Reviewer Comment: "The paper didn’t mention that you have to set credentials before accessing the data, and didn’t provide any instructions on how to do so. I only discovered this when I got an error trying to run the `pull_data_synapse()` line of code.

I had to go to the Synapse site and figure out how to register, and then come back to R and run `set_synapse_credentials()` before I could run `pull_data_synapse()`. The package would be improved by including in the below error instructions on where and how to get credentials. Based on the error message I got, I went to the help file for `set_synapse_credentials()` but there were no details. That is another place where more useful information about how to get credentials could be included."

- [ ] Add instruction on how to get credentials in paper
- [ ] Improve error message on `set_synapse_credentials()` on where and how to get credentials 
- [ ] Improve help file (and maybe vignettes) of `set_synapse_credentials()`
- [ ] Update `README.md` with more details about how to authenticate and second terms of service
- [ ] Update `pull_data_synapse` help file with more details about how to auth and second terms of service

@slb2240 feel free to add a comment here with any proposed language for the term of service bit. Thanks!

**Comment by slb2240** [comment]
In the README we currently have:

 "For public data releases:
  
  Register for a [Synapse account](https://www.synapse.org/#)
  
  Navigate to the data release and request accept terms of use (e.g., for the NSCLC 2.0-public data release, navigate to the [Synapse page](https://www.synapse.org/#!Synapse:syn27056697) for the data release). Towards the top of the page, there is information including the Synapse ID, DOI, Item count, and Access. Next to Access is a link that reads Request Access.
  
  Select Request Access, review the terms of data use and select Accept"

Thoughts on adding a sentence: "Note that permissions for Synapse and permissions for each data release are distinct. Both permissions must be accepted to successfully access the data."
