### ISSUE TITLE
Review access requirements with new test email

### ISSUE THREAD

**Issue by karissawhiting** [GENIE-BPC/genieBPC#67]
Relevant Reviewer Comment:  "Even after registering on Synapse, I got an error when I tried to run the `pull_data_synapse()` line of code in your paper, saying I had unmet access requirements (see below). I had already accepted all of the terms of use at Synapse, and the error message didn’t include any details on how to resolve the issue. After some digging, I found that I actually had to navigate to the download page for the dataset in question – NSCLC v2.0-public - and click the “Request Access” link and agree to something else before I could successfully run `pull_data_request()`. More helpful error messages and/or help file information would be really beneficial here."

Test this out with a new email and revise error messages to be more clear on terms of service for data sets.

**Comment by karissawhiting** [comment]
@jalavery If you get a chance to try this out with a new email, can you screenshot the process of accepting terms for our records? We can discuss and I can updated docs as needed.

**Comment by jalavery** [comment]
Note that we tried this and found that there are two sets of terms of use that need to be accepted:
1. Terms of use when you create a Synapse acct
2. Terms of use for each dataset

Clarified this in the vignettes, readme, and in manuscript.
